# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e82b3020f4b1ecca7452ad9ec6e204c7b808c107f6a266e3235a9288427fcbc51ad45074c2712209fb277edd9b0bc73cae03c598b7a6317782d3369911d9c899

test:
  secret_key_base: 2f11c52cd7d10c3c361f1538e59879baee292cde5161d1a4aebc21f133869cce05b31fabf8477e5b2589edbbea8e944b5df1407e7a8561cd21c6a0791f6bc7bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
